#!/usr/bin/env bash
if [ -z "$SKIPAUTOGEN" ]; then
CFLAGS="-DCONFIG_SOAP" \
./autogen.sh \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --enable-ifupdown \
    --enable-ppp \
    --with-dhclient=yes \
    --with-resolvconf=yes
  if [ "$?" -ne 0 ]; then
  exit 1;
  fi
fi
make &&
make check &&
sudo service network-manager stop
if [ -n "$CLEARSYSLOG" ]; then
echo "" | sudo tee /var/log/syslog
  if [ "$?" -ne 0 ]; then
  exit 1;
  fi
fi
sudo make install &&
sudo service network-manager start

#    --enable-polkit \
#    --enable-modify-system \
